version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "Hello world!"
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/my-website
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync ~/my-website/dist s3://drewclam.com --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      # - build
      - deploy:
          context: aws-cli
          # requires:
          #   - build
          filters:
            branches:
              only: master
