version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache
      - run:
          name: Install dependencies
          command: sudo npm install
      - save_cache:
          key: dependency-cache
          paths:
            - node_modules
      - run:
          name: Test
          command: npm run test
      - run:
          name: Bundle
          command: npm run build:ci
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - attach_workspace:
          at: ./
      - add_ssh_keys:
          fingerprints:
            - "a5:f2:40:03:79:a5:6f:78:66:6c:6f:ae:f6:65:9f:17"
      - run:
          name: Write SSH
          command: echo '<hostname> <type> <key>' >> ~/.ssh/known_hosts
      - run:
          name: SCP to EC2
          command: scp -oStrictHostKeyChecking=no -r ~/project/dist ec2-user@ec2-35-183-4-48.ca-central-1.compute.amazonaws.com:~/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          context: aws-cli
          requires:
            - build
          filters:
            branches:
              only: master
